const SIGNUP = 'SIGNUP';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const VERIFY_EMAIL = 'VERIFY_EMAIL';
const LANGUAGES = 'LANGUAGES';
const ADD_DOCUMENT = 'ADD_DOCUMENT';
const UPLOAD_DOCUMENT = 'UPLOAD_DOCUMENT';
const EDIT_DOCUMENT = 'EDIT_DOCUMENT';
const GET_USER_DOCUMENT = 'GET_USER_DOCUMENT';
const DEL_DOCUMENT = 'DEL_DOCUMENT';
const GET_ALL_VOICES = 'GET_ALL_VOICES';
const GET_ALL_GENRES = 'GET_ALL_GENRES';
const SEND_VERIF_CODE = 'SEND_VERIF_CODE';
const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
const TRANSLATION_FORM_DATA = 'TRANSLATION_FORM_DATA';
const SET_DOC_FOR_PLAYER = 'SET_DOC_FOR_PLAYER';
const GET_USER_PLAYLISTS = 'GET_USER_PLAYLISTS';
const CREATE_PLAYLIST = 'CREATE_PLAYLIST';
const SET_PLAYER_OBJECT = 'SET_PLAYER_OBJECT';
export {
  LOGIN,
  LOGOUT,
  SIGNUP,
  VERIFY_EMAIL,
  LANGUAGES,
  ADD_DOCUMENT,
  UPLOAD_DOCUMENT,
  EDIT_DOCUMENT,
  GET_USER_DOCUMENT,
  DEL_DOCUMENT,
  GET_ALL_VOICES,
  GET_USER_PLAYLISTS,
  GET_ALL_GENRES,
  SEND_VERIF_CODE,
  UPDATE_PASSWORD,
  TRANSLATION_FORM_DATA,
  SET_DOC_FOR_PLAYER,
  CREATE_PLAYLIST,
  SET_PLAYER_OBJECT,
};
